name: Build Plugins

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
   name: Building
   runs-on: ubuntu-latest
   steps:
   - name: Checkout sources
     uses: actions/checkout@v3
     with:
          fetch-depth: 0
          submodules: recursive
   - run: | 
           sudo apt install build-essential -y
           cd building/scripting/
           ./compile.sh
   - name: Upload artifacts
     uses: actions/upload-artifact@v2
     with:
          name: plugin-compiled
          path: building/scripting/compiled
